### ISSUE TITLE
Lua Fehler bei Ställen

### ISSUE THREAD

**Issue by BauerEnni** [Achimobil/FS25_InfoDisplayExtension#1]
[log.txt](https://github.com/user-attachments/files/17784954/log.txt)

Hallo Achim.

Anbei meine Log Datei.

Alsoder Lua Fehler tritt bei den Hühnern und Schafen auf,sobald ich mich den Ställen nähere.
Und hier noch die Screenshots dazu.

Lg Sven

![20241116142756_1](https://github.com/user-attachments/assets/b217f258-8a04-44eb-99ee-0ec8666c2207)
![20241116142910_1](https://github.com/user-attachments/assets/6e1c7986-08c2-437f-98ac-13be501cff1b)

**Comment by Achimobil** [comment]
Nachstellbar und behoben
