### ISSUE TITLE
[SUGESSTION] Crop Growth Stage Info / Feldfrucht Wachstumsphase

### ISSUE THREAD

**Issue by CODUMO** [Achimobil/FS25_InfoDisplayExtension#12]
Hallo Achim,

danke für deine Arbeit für die Modding Community rund um den LS.
Ich wollte vorschlagen ob es möglich wäre, die aktuelle Wachstumsphase eines Feldes mit in das Info Display aufzunehmen.
Im LS22 gab es dafür einen separaten Mod. Ich denke aber das könnte hier gut integriert werden.
https://www.farming-simulator.com/mod.php?lang=fr&country=fr&mod_id=232903 

Danke und Gruß
CODUMO

**Comment by MisterMedion** [comment]
Hey Zusammen, ja den Vorschlag von Codumo find ich super. Dies wäre sehr wünschenswert

**Comment by Achimobil** [comment]
> Hey Zusammen, ja den Vorschlag von Codumo find ich super. Dies wäre sehr wünschenswert. Aber vielleicht nicht nur die Wachstumsstufe sondern auch die Düngestufe

Düngestufe is sinnlos, weil die ja bereits da steht, es gibt ja nur 50% und 100% und wo nix steht ist diese 0

**Comment by Achimobil** [comment]
> Hallo Achim Habe mich schon gefreut dass die Wachstumsphase bei den Bäumen jetzt funktioniert hat und FS25 nicht eingefroren ist. Aber jetzt sind die Küstenkiefern von der Phase 3 in die 4 gekommen und FS25 friert wieder ein. Ohne deinem tollen Mod funktioniert es ohne Probleme.
> 
> Grüße aus Ungarn Deutscher Rentner spielt Bauer :-)

Das hat nichts mit dem ticket hier zu tun. Werde ich später hier löschen.
Eigenes Ticket anlegen mit Log, Bild wo man sieht wo das ist und das savegame.
