### ISSUE TITLE
Planted Tree bug from lua script

### ISSUE THREAD

**Issue by gregorcinkelj** [Achimobil/FS25_InfoDisplayExtension#13]
Hi 
i enjoy your mod and i found a bug with the planted trees you do in fs 25 it gives me error when you look at a tree but when your near it it works normally

i added screenshot so you can see the error hopefully
![Farming Simulator 2025 Screenshot 2024 11 30 - 13 23 07 35](https://github.com/user-attachments/assets/95e0dc88-4238-4858-beee-b53baec22ce1)

**Comment by Achimobil** [comment]
Hint: The search is not for nothing ;)
