### ISSUE TITLE
Bug With Planted Trees?

### ISSUE THREAD

**Issue by LFC180** [Achimobil/FS25_InfoDisplayExtension#14]
I planted some trees and when they reached their 1st growth stage, anytime I go to the trees my games freezes. When i checked the log this error was showing:

C:/Users/USER/Documents/My Games/FarmingSimulator2025/mods/FS25_InfoDisplayExtension/InfoDisplayExtension.lua:848: invalid argument #1 to 'getn' (table expected, got nil)
2024-11-30 17:29 Error: Running LUA method 'update'. ### 

My game doesn't freeze when I disable this mod. is there a fix for this.

thank you

**Comment by raider2711** [comment]
Happened to me too, I took a recording of it. ( https://medal.tv/games/farming-simulator-25/clips/jbSxqT8z5eyoAEZMv?invite=cr-MSxaNTQsMTkwOTM1MDUs ) 


The first clip is me looking at the same trees without the mod activated. I am able to look at the trees and move around after.

The second clip is with the mod activated, I walk up to the tree and cant move at all, luckily you're able to press esc and go to the main menu.

**Comment by Achimobil** [comment]
The search function has a reason. So please use it instead of wasting time

**Comment by LFC180** [comment]
Whatever asshole

**Comment by raider2711** [comment]
You could always make a "Known bugs" section so you don't have to deal with this. Also the original posting for this issue is in another language, I would have never found it.

**Comment by Achimobil** [comment]
but there are already 2 other posts which are pointing to #4 as duplicates. 
Search before Posting will find in just search for tree for example.

**Comment by Achimobil** [comment]
Oh, insults from one and a thumbs down from the other? Do I really have to put the rules that are generally accepted on the internet in the mod description?
