### ISSUE TITLE
Spielfigur friert ein

### ISSUE THREAD

**Issue by dualemotive** [Achimobil/FS25_InfoDisplayExtension#15]
Ab der ersten Wachstumsphase eines selbst gepflanzten Baum, friert der Spielchrakter ein wenn man direkt auf den Baum schaut.
Festgestellt bei Küstenkiefer.

**Comment by Achimobil** [comment]
Schau dir bitte den Fehler in deiner log an und  wenn das der ist der auch in #4 steht, dann ist der bekannt, dann bitte ticket schließen und wenn es nicht der ist, dann bitte volle log anhängen
