### ISSUE TITLE
Bei mir kommt in der Log dieser Fehler

### ISSUE THREAD

**Issue by Nonscheff** [Achimobil/FS25_InfoDisplayExtension#20]
Error: Invalid mod name 'FS25_InfoDisplayExtension-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

**Comment by Achimobil** [comment]
Man muss mods schon richtig verpacken. Man kann nicht einfach ein Git Repro runter laden und in den mods order packen. Das hier sollte helfen: https://youtu.be/qG8wNBkjB3w
