### ISSUE TITLE
Anzeige von Silo-Status und Futtermischwagen 

### ISSUE THREAD

**Issue by Firefall666** [Achimobil/FS25_InfoDisplayExtension#21]
Die Anzeige von Silo Status (Gären % und Füllmenge) sowie die Anzeige eines Futtermischwagens bei ausgeschaltetem F1-Menü wäre ein sehr schönes Feature.

**Comment by Achimobil** [comment]
I checked it and this in not possible.

Bunker Silos do no have any info trigger so it is not possible to show anything on them.

Mixer Wagons show a lot in the F1 Menü and it makes no sense to show this all in the info box. It is for a reason in the F1 Menu.
