### ISSUE TITLE
Translation pt-pt

### ISSUE THREAD

**Issue by Inoque71** [Achimobil/FS25_InfoDisplayExtension#22]
Hello, This are the translation pt-pt for next update.
Regards

[translation_pt.zip](https://github.com/user-attachments/files/18100555/translation_pt.zip)

**Comment by Achimobil** [comment]
Thanks, I have put then im the main branch for the next update or when you build it yourself

**Comment by Inoque71** [comment]
Hello,
I try to correct the line you add on translation, but was not working. So this is the update. You can use the same line on br-br
Thanks
[translation_pt.zip](https://github.com/user-attachments/files/18195639/translation_pt.zip)

**Comment by Achimobil** [comment]
I changed it for the next update
