### ISSUE TITLE
Lua error beim anschauen von selbst geplantzten bäumen mit setzlings maschiene

### ISSUE THREAD

**Issue by Fiffi1983** [Achimobil/FS25_InfoDisplayExtension#4]
FarmingSimulator2025/mods/FS25_InfoDisplayExtension/InfoDisplayExtension.lua:848: invalid argument #1 to 'getn' (table expected, got nil)
hoffe du kannst so etwas damit anfangen
mfg  fiffi1883

**Comment by Achimobil** [comment]
nope. Der Fehler wurde schon letzte Woche behoben und sollte in der ModHub Version nicht mehr da sein.
Wenn du die ModHub Version nutzt, bitte volle log einstellen.

**Comment by Achimobil** [comment]
Brauch keine Log oder weitere infos mehr. In der ModHub version konnte ich das nachstellen.

**Comment by Achimobil** [comment]
Gefixed und wartet jetzt auf nächstes Update im ModHub

**Comment by LamaiK** [comment]
Der Fehler tritt jetzt doch noch bei der letzten Wachstumsstufe (Ausgewachsen 6/6) auf.
Baum Typ: PINUSSYLVESTRIS Map : USmap
Habe deine neue V. 1.0.0.4 benutzt.

[log.txt](https://github.com/user-attachments/files/17916510/log.txt)
mfg Lamai

**Comment by Achimobil** [comment]
Restzeitberechnung ist schwer, wenn es keine restzeit gibt. gefixed und eingecheckt in 1.0.0.5

**Comment by Achimobil** [comment]
Die 1.0.1.0 ist im ModHub eingereicht, deshalb close ich das hier jetzt
