### ISSUE TITLE
[SUGGESTION] Add Weight

### ISSUE THREAD

**Issue by blubstar86** [Achimobil/FS25_InfoDisplayExtension#9]
Hello Achim,

thank you for all the mods you made for FS22 and hopefully for FS25 to.

I would love to see the weight of tools or tractors in the InfoDisplay.

Have a nice day
TY

![Screenshot 2024-11-21 184033](https://github.com/user-attachments/assets/d047ab71-0a62-4235-bdb7-26cbbd175d59)

**Comment by Achimobil** [comment]
I added the current Weight in tons to all vehicles with 1.0.1.7 for the nextt ModHub Version
